import type {
  Alert,
  BlackoutCheck,
  LiquidityPool,
  NewsEvent,
  PerformanceStats,
  TradeJournalEntry,
  UserProfile,
  UserSetup,
  WatchlistDetail,
  WeeklyStory,
} from './types';

export const CURRENT_USER_PROFILE: UserProfile = {
  id: 'user-001',
  email: 'trader@ecott.example',
  account_balance_usd: '25000.00',
  default_risk_percentage: '0.0100',
  primary_trading_pair: 'EURUSD',
  preferred_pairs: ['EURUSD', 'GBPUSD', 'USDJPY', 'DXY'],
  timezone: 'America/New_York',
  experience_level: 'intermediate',
};

export const PRIMARY_WATCHLIST: WatchlistDetail = {
  id: 'watchlist-primary',
  user_id: CURRENT_USER_PROFILE.id,
  name: 'Majors',
  description: 'Eight tracked pairs across the platform.',
  created_at: '2026-05-01T14:00:00Z',
  items: [
    {
      pair_code: 'EURUSD',
      sort_order: 0,
      latest_report_date: '2026-05-26',
      bias_direction: 'bullish',
      bias_strength: 'strongly',
      bias_statement_text:
        'EUR/USD bias is STRONGLY BULLISH. Asset Managers continue accumulating with 3+ weeks of net-long expansion.',
      phase: 3,
      phase_confidence: 'confirmed',
      phase_confidence_percentage: '88.0',
      leveraged_funds_cot_index_value: '92.5',
      active_setup_count: 2,
      active_liquidity_pool_count: 5,
    },
    {
      pair_code: 'GBPUSD',
      sort_order: 1,
      latest_report_date: '2026-05-26',
      bias_direction: 'bearish',
      bias_strength: 'moderately',
      bias_statement_text:
        'GBP/USD bias is MODERATELY BEARISH. Asset Managers reducing longs while LF flips short.',
      phase: 5,
      phase_confidence: 'developing',
      phase_confidence_percentage: '72.0',
      leveraged_funds_cot_index_value: '14.2',
      active_setup_count: 1,
      active_liquidity_pool_count: 3,
    },
    {
      pair_code: 'USDJPY',
      sort_order: 2,
      latest_report_date: '2026-05-26',
      bias_direction: 'bullish',
      bias_strength: 'moderately',
      bias_statement_text: 'USD/JPY bias is MODERATELY BULLISH. Asset Managers steadily adding longs.',
      phase: 3,
      phase_confidence: 'confirmed',
      phase_confidence_percentage: '85.0',
      leveraged_funds_cot_index_value: '78.4',
      active_setup_count: 0,
      active_liquidity_pool_count: 2,
    },
    {
      pair_code: 'DXY',
      sort_order: 3,
      latest_report_date: '2026-05-26',
      bias_direction: 'bearish',
      bias_strength: 'strongly',
      bias_statement_text:
        'DXY bias is STRONGLY BEARISH. Cross-report rotation with EUR/USD confirmed institutional dollar selling.',
      phase: 5,
      phase_confidence: 'high_conviction',
      phase_confidence_percentage: '95.0',
      leveraged_funds_cot_index_value: '8.1',
      active_setup_count: 1,
      active_liquidity_pool_count: 4,
    },
    {
      pair_code: 'AUDUSD',
      sort_order: 4,
      latest_report_date: '2026-05-26',
      bias_direction: 'neutral',
      bias_strength: 'tentatively',
      bias_statement_text: 'AUD/USD bias is TENTATIVELY NEUTRAL. No clear institutional conviction.',
      phase: 2,
      phase_confidence: 'transitional',
      phase_confidence_percentage: '42.0',
      leveraged_funds_cot_index_value: '52.0',
      active_setup_count: 0,
      active_liquidity_pool_count: 1,
    },
  ],
};

export const SECONDARY_WATCHLISTS: WatchlistDetail[] = [
  {
    id: 'watchlist-focus',
    user_id: CURRENT_USER_PROFILE.id,
    name: 'This week focus',
    description: 'Pairs with high-conviction setups.',
    created_at: '2026-05-20T14:00:00Z',
    items: PRIMARY_WATCHLIST.items.filter((item) => item.active_setup_count > 0),
  },
  {
    id: 'watchlist-bearish',
    user_id: CURRENT_USER_PROFILE.id,
    name: 'Bearish bias',
    description: 'Pairs where the COT bias is bearish right now.',
    created_at: '2026-05-15T14:00:00Z',
    items: PRIMARY_WATCHLIST.items.filter((item) => item.bias_direction === 'bearish'),
  },
];

export const ALL_WATCHLISTS: WatchlistDetail[] = [PRIMARY_WATCHLIST, ...SECONDARY_WATCHLISTS];

export const ACTIVE_SETUPS: UserSetup[] = [
  {
    id: 'setup-001',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    model: 'fibonacci_retracement',
    direction: 'long',
    swing_high: '1.16200',
    swing_low: '1.13900',
    entry_zone_low: '1.14250',
    entry_zone_high: '1.14400',
    stop_loss_price: '1.13852',
    target_1_price: '1.15400',
    target_2_price: '1.16200',
    target_3_price: '1.17100',
    confluence_score: '7.5',
    confluence_classification: 'high_conviction_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '1.0', passed: true },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0.5', passed: true },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '1.0', passed: true },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '1.0', passed: true },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: 'Strong AM accumulation aligned with LF flipping long at extreme.',
    activated_at: '2026-05-27T13:30:00Z',
    closed_at: null,
    created_at: '2026-05-27T13:30:00Z',
    updated_at: '2026-05-27T13:30:00Z',
  },
  {
    id: 'setup-002',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'GBPUSD',
    model: 'structure_break_and_retest',
    direction: 'short',
    swing_high: '1.32500',
    swing_low: '1.28800',
    entry_zone_low: '1.30800',
    entry_zone_high: '1.31000',
    stop_loss_price: '1.31408',
    target_1_price: '1.29800',
    target_2_price: '1.28800',
    target_3_price: null,
    confluence_score: '4.5',
    confluence_classification: 'active_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '0', passed: false },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0.5', passed: true },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '0', passed: false },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '0', passed: false },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: null,
    activated_at: '2026-05-28T09:15:00Z',
    closed_at: null,
    created_at: '2026-05-28T09:15:00Z',
    updated_at: '2026-05-28T09:15:00Z',
  },
  {
    id: 'setup-003',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'DXY',
    model: 'divergence_fade',
    direction: 'short',
    swing_high: '108.50',
    swing_low: '104.20',
    entry_zone_low: '107.20',
    entry_zone_high: '107.40',
    stop_loss_price: '108.08',
    target_1_price: '105.50',
    target_2_price: '104.20',
    target_3_price: null,
    confluence_score: '6.0',
    confluence_classification: 'high_conviction_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '1.0', passed: true },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0', passed: false },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '0', passed: false },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '1.0', passed: true },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: 'Cross-report rotation with EUR/USD confirmed.',
    activated_at: '2026-05-27T15:00:00Z',
    closed_at: null,
    created_at: '2026-05-27T15:00:00Z',
    updated_at: '2026-05-27T15:00:00Z',
  },
];

export const CLOSED_SETUPS: UserSetup[] = [
  {
    ...ACTIVE_SETUPS[0],
    id: 'setup-closed-001',
    status: 'closed_target_1_hit',
    closed_at: '2026-05-20T16:45:00Z',
    activated_at: '2026-05-18T13:00:00Z',
    created_at: '2026-05-18T13:00:00Z',
    updated_at: '2026-05-20T16:45:00Z',
  },
  {
    ...ACTIVE_SETUPS[1],
    id: 'setup-closed-002',
    status: 'closed_stopped_out',
    closed_at: '2026-05-15T10:20:00Z',
    activated_at: '2026-05-14T09:30:00Z',
    created_at: '2026-05-14T09:30:00Z',
    updated_at: '2026-05-15T10:20:00Z',
  },
];

export const ALL_SETUPS: UserSetup[] = [...ACTIVE_SETUPS, ...CLOSED_SETUPS];

export const TRADE_JOURNAL_ENTRIES: TradeJournalEntry[] = [
  {
    id: 'journal-001',
    user_id: CURRENT_USER_PROFILE.id,
    setup_id: 'setup-closed-001',
    close_price: '1.15400',
    r_multiple: '2.10',
    pips_gained: '108.0',
    outcome: 'win',
    closed_at: '2026-05-20T16:45:00Z',
    reflection_notes:
      'Entry hit on third 4H rejection. Held through London open consolidation; target 1 hit during NY session.',
    lessons_learned:
      'Scaling out at target 1 with stop to breakeven preserved the win when price reversed before target 2.',
    screenshots: [],
    created_at: '2026-05-20T16:45:00Z',
    updated_at: '2026-05-20T18:00:00Z',
  },
  {
    id: 'journal-002',
    user_id: CURRENT_USER_PROFILE.id,
    setup_id: 'setup-closed-002',
    close_price: '1.31408',
    r_multiple: '-1.00',
    pips_gained: '-60.8',
    outcome: 'loss',
    closed_at: '2026-05-15T10:20:00Z',
    reflection_notes:
      'Stop taken cleanly. Bias-aligned but the structural break was shallow — not a true breakout.',
    lessons_learned:
      'Wait for the daily close before treating a structure break as confirmed; intraday wicks alone are noise.',
    screenshots: [],
    created_at: '2026-05-15T10:20:00Z',
    updated_at: '2026-05-15T11:30:00Z',
  },
];

export const PERFORMANCE_STATS: PerformanceStats = {
  total_trades: 12,
  wins: 7,
  losses: 4,
  break_evens: 1,
  win_rate_percentage: '63.6',
  average_r_multiple: '0.85',
  total_r_multiple: '10.20',
  expectancy_r_multiple: '0.85',
  largest_win_r_multiple: '3.20',
  largest_loss_r_multiple: '-1.00',
  current_streak_length: 2,
  current_streak_outcome: 'win',
  by_pair_code: {
    EURUSD: {
      total_trades: 5,
      wins: 4,
      losses: 1,
      break_evens: 0,
      win_rate_percentage: '80.0',
      average_r_multiple: '1.70',
    },
    GBPUSD: {
      total_trades: 4,
      wins: 2,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '50.0',
      average_r_multiple: '0.10',
    },
    DXY: {
      total_trades: 3,
      wins: 1,
      losses: 1,
      break_evens: 1,
      win_rate_percentage: '50.0',
      average_r_multiple: '0.40',
    },
  },
  by_setup_model: {
    fibonacci_retracement: {
      total_trades: 7,
      wins: 5,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '71.4',
      average_r_multiple: '1.25',
    },
    structure_break_and_retest: {
      total_trades: 3,
      wins: 1,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '33.3',
      average_r_multiple: '-0.20',
    },
    divergence_fade: {
      total_trades: 2,
      wins: 1,
      losses: 0,
      break_evens: 1,
      win_rate_percentage: '100.0',
      average_r_multiple: '1.10',
    },
  },
};

export const ALERT_INBOX: Alert[] = [
  {
    id: 'alert-001',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'high_conviction_setup',
    severity: 'critical',
    title: 'High-conviction setup: EUR/USD',
    body: 'EUR/USD setup scored 7.5 confluence points. Review and consider entry.',
    payload_json: { setup_id: 'setup-001', pair_code: 'EURUSD', confluence_score: '7.5' },
    is_read: false,
    read_at: null,
    created_at: '2026-05-27T13:30:00Z',
  },
  {
    id: 'alert-002',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'cot_phase_transition',
    severity: 'notable',
    title: 'GBP/USD phase shift: 4 → 5',
    body: 'The institutional cycle for GBP/USD advanced from phase 4 to phase 5 on the 2026-05-26 COT report.',
    payload_json: {
      pair_code: 'GBPUSD',
      previous_phase: 4,
      new_phase: 5,
      cot_report_date: '2026-05-26',
    },
    is_read: false,
    read_at: null,
    created_at: '2026-05-26T20:00:00Z',
  },
  {
    id: 'alert-003',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'cross_report_rotation',
    severity: 'notable',
    title: 'Cross-report rotation confirmed: EUR/USD ↔ DXY',
    body: 'Positioning rotated in opposing directions — institutional conviction is consistent across both.',
    payload_json: {
      primary_pair_code: 'EURUSD',
      counterpart_pair_code: 'DXY',
      cot_report_date: '2026-05-26',
    },
    is_read: false,
    read_at: null,
    created_at: '2026-05-26T20:00:00Z',
  },
  {
    id: 'alert-004',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'target_hit',
    severity: 'notable',
    title: 'EUR/USD target hit',
    body: 'EUR/USD setup closed at 1.15400 (+2.10R). Status: closed_target_1_hit.',
    payload_json: {
      setup_id: 'setup-closed-001',
      pair_code: 'EURUSD',
      r_multiple: '2.10',
      terminal_status: 'closed_target_1_hit',
    },
    is_read: true,
    read_at: '2026-05-20T17:00:00Z',
    created_at: '2026-05-20T16:45:00Z',
  },
  {
    id: 'alert-005',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'stop_hit',
    severity: 'notable',
    title: 'GBP/USD stop hit',
    body: 'GBP/USD setup closed at 1.31408 (-1.00R). Status: closed_stopped_out.',
    payload_json: {
      setup_id: 'setup-closed-002',
      pair_code: 'GBPUSD',
      r_multiple: '-1.00',
      terminal_status: 'closed_stopped_out',
    },
    is_read: true,
    read_at: '2026-05-15T11:00:00Z',
    created_at: '2026-05-15T10:20:00Z',
  },
];

export const LIQUIDITY_POOLS: LiquidityPool[] = [
  {
    id: 'pool-001',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    kind: 'buy_side_liquidity',
    pool_type: 'weekly_high_low',
    timeframe: 'weekly',
    price_level: '1.16200',
    zone_upper_price: '1.16250',
    zone_lower_price: '1.16150',
    obviousness_rating: 5,
    is_untested: true,
    time_at_level: 'multiple_hours',
    is_cot_direction_aligned: true,
    timeframe_visibility_count: 3,
    validation_score: '92.5',
    classification: 'primary_target',
    status: 'active',
    notes: 'Previous weekly high — stops cluster expected.',
    created_at: '2026-05-25T20:00:00Z',
  },
  {
    id: 'pool-002',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    kind: 'sell_side_liquidity',
    pool_type: 'daily_high_low',
    timeframe: 'daily',
    price_level: '1.13900',
    zone_upper_price: null,
    zone_lower_price: null,
    obviousness_rating: 4,
    is_untested: true,
    time_at_level: 'few_candles',
    is_cot_direction_aligned: false,
    timeframe_visibility_count: 2,
    validation_score: '68.1',
    classification: 'significant_pool',
    status: 'active',
    notes: null,
    created_at: '2026-05-26T14:00:00Z',
  },
  {
    id: 'pool-003',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'DXY',
    kind: 'fair_value_gap',
    pool_type: 'swing_high_low',
    timeframe: 'four_hour',
    price_level: '107.80',
    zone_upper_price: '107.85',
    zone_lower_price: '107.75',
    obviousness_rating: 3,
    is_untested: true,
    time_at_level: 'single_candle',
    is_cot_direction_aligned: true,
    timeframe_visibility_count: 1,
    validation_score: '52.3',
    classification: 'moderate_pool',
    status: 'active',
    notes: null,
    created_at: '2026-05-28T11:30:00Z',
  },
];

export const UPCOMING_NEWS_EVENTS: NewsEvent[] = [
  {
    id: 'news-001',
    source: 'forex_factory',
    source_event_id: 'ff-nfp-2026-06-05',
    event_at: '2026-06-05T12:30:00Z',
    currency: 'USD',
    impact: 'high',
    name: 'Non-Farm Payrolls',
    description: 'Monthly change in employed people, excluding farming, government and private households.',
  },
  {
    id: 'news-002',
    source: 'forex_factory',
    source_event_id: 'ff-fomc-2026-06-12',
    event_at: '2026-06-12T18:00:00Z',
    currency: 'USD',
    impact: 'high',
    name: 'FOMC Statement',
    description: 'Federal Open Market Committee rate decision and statement.',
  },
  {
    id: 'news-003',
    source: 'forex_factory',
    source_event_id: 'ff-ecb-2026-06-06',
    event_at: '2026-06-06T11:45:00Z',
    currency: 'EUR',
    impact: 'high',
    name: 'ECB Main Refinancing Rate',
    description: 'European Central Bank interest rate decision.',
  },
  {
    id: 'news-004',
    source: 'forex_factory',
    source_event_id: 'ff-cpi-2026-06-10',
    event_at: '2026-06-10T12:30:00Z',
    currency: 'USD',
    impact: 'high',
    name: 'Core CPI m/m',
    description: 'Change in price of goods and services purchased by consumers, excluding food and energy.',
  },
];

export const CURRENT_BLACKOUT_CHECK: BlackoutCheck = {
  pair_code: 'EURUSD',
  evaluated_at: new Date().toISOString(),
  in_blackout: false,
  minutes_until_event: null,
  minutes_since_event: null,
  triggering_event: null,
};

export const CURRENT_WEEK_STORY: WeeklyStory = {
  pair_code: 'EURUSD',
  report_date: '2026-05-26',
  chapter_1_text:
    'The 2026-05-26 COT report shows EUR/USD bias is STRONGLY BULLISH. Asset Managers continue accumulating with the eighth consecutive week of net-long expansion. Leveraged Funds joined the long side at extreme levels (COT Index 92.5), confirming institutional conviction across categories. Cross-report rotation with DXY is confirmed.',
  chapter_2_text: null,
  chapter_3_text: null,
  chapter_4_text: null,
  chapter_5_text: null,
  updated_at: '2026-05-26T20:00:00Z',
};
