import type {
  Alert,
  CommodityAnalysis,
  CommodityHistoryPoint,
  CurrencyStrengthMatrix,
  DivergenceAlert,
  FundamentalScore,
  FundamentalTrend,
  IndexReport,
  LiquidityPool,
  MarketCode,
  MarketDefinition,
  MultiAssetOverview,
  PerformanceStats,
  RiskSentiment,
  TradeJournalEntry,
  UserProfile,
  UserSetup,
  WatchlistDetail,
} from './types';

export const CURRENT_USER_PROFILE: UserProfile = {
  id: 'user-001',
  email: 'trader@ecott.example',
  account_balance_usd: '25000.00',
  default_risk_percentage: '0.0100',
  primary_trading_pair: 'EURUSD',
  preferred_pairs: ['EURUSD', 'GBPUSD', 'USDJPY', 'DXY'],
  timezone: 'America/New_York',
  experience_level: 'intermediate',
  notification_preferences: {},
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
};

export const PRIMARY_WATCHLIST: WatchlistDetail = {
  id: 'watchlist-primary',
  user_id: CURRENT_USER_PROFILE.id,
  name: 'Majors',
  description: 'Eight tracked pairs across the platform.',
  created_at: '2026-05-01T14:00:00Z',
  items: [
    {
      pair_code: 'EURUSD',
      sort_order: 0,
      latest_report_date: '2026-05-26',
      bias_direction: 'bullish',
      bias_strength: 'strongly',
      bias_statement_text:
        'EUR/USD bias is STRONGLY BULLISH. Asset Managers continue accumulating with 3+ weeks of net-long expansion.',
      phase: 3,
      phase_confidence: 'confirmed',
      phase_confidence_percentage: '88.0',
      leveraged_funds_cot_index_value: '92.5',
      active_setup_count: 2,
      active_liquidity_pool_count: 5,
    },
    {
      pair_code: 'GBPUSD',
      sort_order: 1,
      latest_report_date: '2026-05-26',
      bias_direction: 'bearish',
      bias_strength: 'moderately',
      bias_statement_text:
        'GBP/USD bias is MODERATELY BEARISH. Asset Managers reducing longs while LF flips short.',
      phase: 5,
      phase_confidence: 'developing',
      phase_confidence_percentage: '72.0',
      leveraged_funds_cot_index_value: '14.2',
      active_setup_count: 1,
      active_liquidity_pool_count: 3,
    },
    {
      pair_code: 'USDJPY',
      sort_order: 2,
      latest_report_date: '2026-05-26',
      bias_direction: 'bullish',
      bias_strength: 'moderately',
      bias_statement_text: 'USD/JPY bias is MODERATELY BULLISH. Asset Managers steadily adding longs.',
      phase: 3,
      phase_confidence: 'confirmed',
      phase_confidence_percentage: '85.0',
      leveraged_funds_cot_index_value: '78.4',
      active_setup_count: 0,
      active_liquidity_pool_count: 2,
    },
    {
      pair_code: 'DXY',
      sort_order: 3,
      latest_report_date: '2026-05-26',
      bias_direction: 'bearish',
      bias_strength: 'strongly',
      bias_statement_text:
        'DXY bias is STRONGLY BEARISH. Cross-report rotation with EUR/USD confirmed institutional dollar selling.',
      phase: 5,
      phase_confidence: 'high_conviction',
      phase_confidence_percentage: '95.0',
      leveraged_funds_cot_index_value: '8.1',
      active_setup_count: 1,
      active_liquidity_pool_count: 4,
    },
    {
      pair_code: 'AUDUSD',
      sort_order: 4,
      latest_report_date: '2026-05-26',
      bias_direction: 'neutral',
      bias_strength: 'tentatively',
      bias_statement_text: 'AUD/USD bias is TENTATIVELY NEUTRAL. No clear institutional conviction.',
      phase: 2,
      phase_confidence: 'transitional',
      phase_confidence_percentage: '42.0',
      leveraged_funds_cot_index_value: '52.0',
      active_setup_count: 0,
      active_liquidity_pool_count: 1,
    },
  ],
};

export const SECONDARY_WATCHLISTS: WatchlistDetail[] = [
  {
    id: 'watchlist-focus',
    user_id: CURRENT_USER_PROFILE.id,
    name: 'This week focus',
    description: 'Pairs with high-conviction setups.',
    created_at: '2026-05-20T14:00:00Z',
    items: PRIMARY_WATCHLIST.items.filter((item) => item.active_setup_count > 0),
  },
  {
    id: 'watchlist-bearish',
    user_id: CURRENT_USER_PROFILE.id,
    name: 'Bearish bias',
    description: 'Pairs where the COT bias is bearish right now.',
    created_at: '2026-05-15T14:00:00Z',
    items: PRIMARY_WATCHLIST.items.filter((item) => item.bias_direction === 'bearish'),
  },
];

export const ALL_WATCHLISTS: WatchlistDetail[] = [PRIMARY_WATCHLIST, ...SECONDARY_WATCHLISTS];

export const ACTIVE_SETUPS: UserSetup[] = [
  {
    id: 'setup-001',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    model: 'fibonacci_retracement',
    direction: 'long',
    swing_high: '1.16200',
    swing_low: '1.13900',
    entry_zone_low: '1.14250',
    entry_zone_high: '1.14400',
    stop_loss_price: '1.13852',
    target_1_price: '1.15400',
    target_2_price: '1.16200',
    target_3_price: '1.17100',
    confluence_score: '7.5',
    confluence_classification: 'high_conviction_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '1.0', passed: true },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0.5', passed: true },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '1.0', passed: true },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '1.0', passed: true },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: 'Strong AM accumulation aligned with LF flipping long at extreme.',
    activated_at: '2026-05-27T13:30:00Z',
    closed_at: null,
    created_at: '2026-05-27T13:30:00Z',
    updated_at: '2026-05-27T13:30:00Z',
  },
  {
    id: 'setup-002',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'GBPUSD',
    model: 'structure_break_and_retest',
    direction: 'short',
    swing_high: '1.32500',
    swing_low: '1.28800',
    entry_zone_low: '1.30800',
    entry_zone_high: '1.31000',
    stop_loss_price: '1.31408',
    target_1_price: '1.29800',
    target_2_price: '1.28800',
    target_3_price: null,
    confluence_score: '4.5',
    confluence_classification: 'active_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '0', passed: false },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0.5', passed: true },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '0', passed: false },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '0', passed: false },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: null,
    activated_at: '2026-05-28T09:15:00Z',
    closed_at: null,
    created_at: '2026-05-28T09:15:00Z',
    updated_at: '2026-05-28T09:15:00Z',
  },
  {
    id: 'setup-003',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'DXY',
    model: 'divergence_fade',
    direction: 'short',
    swing_high: '108.50',
    swing_low: '104.20',
    entry_zone_low: '107.20',
    entry_zone_high: '107.40',
    stop_loss_price: '108.08',
    target_1_price: '105.50',
    target_2_price: '104.20',
    target_3_price: null,
    confluence_score: '6.0',
    confluence_classification: 'high_conviction_setup',
    confluence_factors: [
      { name: 'cot_bias_aligned', points_awarded: '2.0', passed: true },
      { name: 'price_at_fib_618', points_awarded: '1.0', passed: true },
      { name: 'price_at_fib_500', points_awarded: '0', passed: false },
      { name: 'divergence_present', points_awarded: '1.0', passed: true },
      { name: 'kill_zone_session', points_awarded: '0', passed: false },
      { name: 'four_hour_rejection', points_awarded: '1.0', passed: true },
      { name: 'structure_fib_double_confluence', points_awarded: '0', passed: false },
      { name: 'leveraged_funds_extreme_or_flip', points_awarded: '1.0', passed: true },
      { name: 'dealer_stop_hunt_wick', points_awarded: '0', passed: false },
    ],
    cot_report_date: '2026-05-26',
    status: 'active',
    notes: 'Cross-report rotation with EUR/USD confirmed.',
    activated_at: '2026-05-27T15:00:00Z',
    closed_at: null,
    created_at: '2026-05-27T15:00:00Z',
    updated_at: '2026-05-27T15:00:00Z',
  },
];

export const CLOSED_SETUPS: UserSetup[] = [
  {
    ...ACTIVE_SETUPS[0],
    id: 'setup-closed-001',
    status: 'closed_target_1_hit',
    closed_at: '2026-05-20T16:45:00Z',
    activated_at: '2026-05-18T13:00:00Z',
    created_at: '2026-05-18T13:00:00Z',
    updated_at: '2026-05-20T16:45:00Z',
  },
  {
    ...ACTIVE_SETUPS[1],
    id: 'setup-closed-002',
    status: 'closed_stopped_out',
    closed_at: '2026-05-15T10:20:00Z',
    activated_at: '2026-05-14T09:30:00Z',
    created_at: '2026-05-14T09:30:00Z',
    updated_at: '2026-05-15T10:20:00Z',
  },
];

export const ALL_SETUPS: UserSetup[] = [...ACTIVE_SETUPS, ...CLOSED_SETUPS];

export const TRADE_JOURNAL_ENTRIES: TradeJournalEntry[] = [
  {
    id: 'journal-001',
    user_id: CURRENT_USER_PROFILE.id,
    setup_id: 'setup-closed-001',
    close_price: '1.15400',
    r_multiple: '2.10',
    pips_gained: '108.0',
    outcome: 'win',
    closed_at: '2026-05-20T16:45:00Z',
    reflection_notes:
      'Entry hit on third 4H rejection. Held through London open consolidation; target 1 hit during NY session.',
    lessons_learned:
      'Scaling out at target 1 with stop to breakeven preserved the win when price reversed before target 2.',
    screenshots: [],
    created_at: '2026-05-20T16:45:00Z',
    updated_at: '2026-05-20T18:00:00Z',
  },
  {
    id: 'journal-002',
    user_id: CURRENT_USER_PROFILE.id,
    setup_id: 'setup-closed-002',
    close_price: '1.31408',
    r_multiple: '-1.00',
    pips_gained: '-60.8',
    outcome: 'loss',
    closed_at: '2026-05-15T10:20:00Z',
    reflection_notes:
      'Stop taken cleanly. Bias-aligned but the structural break was shallow — not a true breakout.',
    lessons_learned:
      'Wait for the daily close before treating a structure break as confirmed; intraday wicks alone are noise.',
    screenshots: [],
    created_at: '2026-05-15T10:20:00Z',
    updated_at: '2026-05-15T11:30:00Z',
  },
];

export const PERFORMANCE_STATS: PerformanceStats = {
  total_trades: 12,
  wins: 7,
  losses: 4,
  break_evens: 1,
  win_rate_percentage: '63.6',
  average_r_multiple: '0.85',
  total_r_multiple: '10.20',
  expectancy_r_multiple: '0.85',
  largest_win_r_multiple: '3.20',
  largest_loss_r_multiple: '-1.00',
  current_streak_length: 2,
  current_streak_outcome: 'win',
  by_pair_code: {
    EURUSD: {
      total_trades: 5,
      wins: 4,
      losses: 1,
      break_evens: 0,
      win_rate_percentage: '80.0',
      average_r_multiple: '1.70',
    },
    GBPUSD: {
      total_trades: 4,
      wins: 2,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '50.0',
      average_r_multiple: '0.10',
    },
    DXY: {
      total_trades: 3,
      wins: 1,
      losses: 1,
      break_evens: 1,
      win_rate_percentage: '50.0',
      average_r_multiple: '0.40',
    },
  },
  by_setup_model: {
    fibonacci_retracement: {
      total_trades: 7,
      wins: 5,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '71.4',
      average_r_multiple: '1.25',
    },
    structure_break_and_retest: {
      total_trades: 3,
      wins: 1,
      losses: 2,
      break_evens: 0,
      win_rate_percentage: '33.3',
      average_r_multiple: '-0.20',
    },
    divergence_fade: {
      total_trades: 2,
      wins: 1,
      losses: 0,
      break_evens: 1,
      win_rate_percentage: '100.0',
      average_r_multiple: '1.10',
    },
  },
};

export const ALERT_INBOX: Alert[] = [
  {
    id: 'alert-001',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'high_conviction_setup',
    severity: 'critical',
    title: 'High-conviction setup: EUR/USD',
    body: 'EUR/USD setup scored 7.5 confluence points. Review and consider entry.',
    payload_json: { setup_id: 'setup-001', pair_code: 'EURUSD', confluence_score: '7.5' },
    is_read: false,
    read_at: null,
    created_at: '2026-05-27T13:30:00Z',
  },
  {
    id: 'alert-002',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'cot_phase_transition',
    severity: 'notable',
    title: 'GBP/USD phase shift: 4 → 5',
    body: 'The institutional cycle for GBP/USD advanced from phase 4 to phase 5 on the 2026-05-26 COT report.',
    payload_json: {
      pair_code: 'GBPUSD',
      previous_phase: 4,
      new_phase: 5,
      cot_report_date: '2026-05-26',
    },
    is_read: false,
    read_at: null,
    created_at: '2026-05-26T20:00:00Z',
  },
  {
    id: 'alert-003',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'cross_report_rotation',
    severity: 'notable',
    title: 'Cross-report rotation confirmed: EUR/USD ↔ DXY',
    body: 'Positioning rotated in opposing directions — institutional conviction is consistent across both.',
    payload_json: {
      primary_pair_code: 'EURUSD',
      counterpart_pair_code: 'DXY',
      cot_report_date: '2026-05-26',
    },
    is_read: false,
    read_at: null,
    created_at: '2026-05-26T20:00:00Z',
  },
  {
    id: 'alert-004',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'target_hit',
    severity: 'notable',
    title: 'EUR/USD target hit',
    body: 'EUR/USD setup closed at 1.15400 (+2.10R). Status: closed_target_1_hit.',
    payload_json: {
      setup_id: 'setup-closed-001',
      pair_code: 'EURUSD',
      r_multiple: '2.10',
      terminal_status: 'closed_target_1_hit',
    },
    is_read: true,
    read_at: '2026-05-20T17:00:00Z',
    created_at: '2026-05-20T16:45:00Z',
  },
  {
    id: 'alert-005',
    user_id: CURRENT_USER_PROFILE.id,
    alert_type: 'stop_hit',
    severity: 'notable',
    title: 'GBP/USD stop hit',
    body: 'GBP/USD setup closed at 1.31408 (-1.00R). Status: closed_stopped_out.',
    payload_json: {
      setup_id: 'setup-closed-002',
      pair_code: 'GBPUSD',
      r_multiple: '-1.00',
      terminal_status: 'closed_stopped_out',
    },
    is_read: true,
    read_at: '2026-05-15T11:00:00Z',
    created_at: '2026-05-15T10:20:00Z',
  },
];

export const LIQUIDITY_POOLS: LiquidityPool[] = [
  {
    id: 'pool-001',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    kind: 'buy_side_liquidity',
    pool_type: 'weekly_high_low',
    timeframe: 'weekly',
    price_level: '1.16200',
    zone_upper_price: '1.16250',
    zone_lower_price: '1.16150',
    obviousness_rating: 5,
    is_untested: true,
    time_at_level: 'multiple_hours',
    is_cot_direction_aligned: true,
    timeframe_visibility_count: 3,
    validation_score: '92.5',
    classification: 'primary_target',
    status: 'active',
    notes: 'Previous weekly high — stops cluster expected.',
    created_at: '2026-05-25T20:00:00Z',
  },
  {
    id: 'pool-002',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'EURUSD',
    kind: 'sell_side_liquidity',
    pool_type: 'daily_high_low',
    timeframe: 'daily',
    price_level: '1.13900',
    zone_upper_price: null,
    zone_lower_price: null,
    obviousness_rating: 4,
    is_untested: true,
    time_at_level: 'few_candles',
    is_cot_direction_aligned: false,
    timeframe_visibility_count: 2,
    validation_score: '68.1',
    classification: 'significant_pool',
    status: 'active',
    notes: null,
    created_at: '2026-05-26T14:00:00Z',
  },
  {
    id: 'pool-003',
    user_id: CURRENT_USER_PROFILE.id,
    pair_code: 'DXY',
    kind: 'fair_value_gap',
    pool_type: 'swing_high_low',
    timeframe: 'four_hour',
    price_level: '107.80',
    zone_upper_price: '107.85',
    zone_lower_price: '107.75',
    obviousness_rating: 3,
    is_untested: true,
    time_at_level: 'single_candle',
    is_cot_direction_aligned: true,
    timeframe_visibility_count: 1,
    validation_score: '52.3',
    classification: 'moderate_pool',
    status: 'active',
    notes: null,
    created_at: '2026-05-28T11:30:00Z',
  },
];

export const CURRENCY_STRENGTH_MATRIX: CurrencyStrengthMatrix = {
  rankings: [
    { rank: 1, currency_code: 'USD', score: '78.0', bias: 'strongly_bullish' },
    { rank: 2, currency_code: 'GBP', score: '65.0', bias: 'bullish' },
    { rank: 3, currency_code: 'AUD', score: '58.0', bias: 'neutral' },
    { rank: 4, currency_code: 'CAD', score: '52.0', bias: 'neutral' },
    { rank: 5, currency_code: 'NZD', score: '48.0', bias: 'neutral' },
    { rank: 6, currency_code: 'CHF', score: '42.0', bias: 'neutral' },
    { rank: 7, currency_code: 'EUR', score: '35.0', bias: 'bearish' },
    { rank: 8, currency_code: 'JPY', score: '22.0', bias: 'strongly_bearish' },
  ],
  best_pair_ideas: [
    { long_currency_code: 'USD', short_currency_code: 'JPY', score_gap: '56.0' },
    { long_currency_code: 'GBP', short_currency_code: 'JPY', score_gap: '43.0' },
    { long_currency_code: 'USD', short_currency_code: 'EUR', score_gap: '43.0' },
  ],
};

export const FUNDAMENTAL_SCORES: Record<string, FundamentalScore> = {
  USD: {
    asset_code: 'USD',
    score_date: '2026-05-27',
    total_score: '78.0',
    bias: 'strongly_bullish',
    phase: 'peak_bullish',
    component_scores: [
      { component: 'interest_rate', score: '85.0', weight: '0.30' },
      { component: 'central_bank_stance', score: '85.0', weight: '0.20' },
      { component: 'economic_growth', score: '73.0', weight: '0.15' },
      { component: 'inflation', score: '100.0', weight: '0.15' },
      { component: 'employment', score: '76.5', weight: '0.10' },
      { component: 'trade_balance', score: '30.0', weight: '0.05' },
      { component: 'political_stability', score: '70.0', weight: '0.05' },
    ],
  },
  JPY: {
    asset_code: 'JPY',
    score_date: '2026-05-27',
    total_score: '22.0',
    bias: 'strongly_bearish',
    phase: 'trough_bearish',
    component_scores: [
      { component: 'interest_rate', score: '18.0', weight: '0.30' },
      { component: 'central_bank_stance', score: '15.0', weight: '0.20' },
      { component: 'economic_growth', score: '30.0', weight: '0.15' },
      { component: 'inflation', score: '40.0', weight: '0.15' },
      { component: 'employment', score: '29.0', weight: '0.10' },
      { component: 'trade_balance', score: '30.0', weight: '0.05' },
      { component: 'political_stability', score: '72.0', weight: '0.05' },
    ],
  },
};

export const USD_TREND: FundamentalTrend = {
  asset_code: 'USD',
  current_score: '78.0',
  change_4_week: '5.0',
  change_12_week: '12.0',
  change_26_week: '20.0',
  consecutive_weeks: 3,
  direction: 'improving',
};

export const DIVERGENCE_ALERTS: DivergenceAlert[] = [
  {
    id: 'divergence-001',
    asset_code: 'EUR',
    pair_code: 'EURUSD',
    divergence_type: 'fundamental_vs_cot',
    severity: 'high',
    fundamental_bias: 'bearish',
    cot_bias: 'bullish',
    magnitude: '22.0',
    message:
      'Divergence — institutions are positioned against the fundamentals. Either fundamentals will deteriorate or institutions get wrong-footed. Reduce size or wait for a COT reversal.',
    detected_date: '2026-05-27',
    resolved_date: null,
  },
  {
    id: 'divergence-002',
    asset_code: 'AUD',
    pair_code: 'AUDUSD',
    divergence_type: 'fundamental_vs_cot',
    severity: 'medium',
    fundamental_bias: 'bullish',
    cot_bias: 'bearish',
    magnitude: '12.0',
    message:
      'Divergence — fundamentals improving but COT still net short. Watch for a COT reversal.',
    detected_date: '2026-05-27',
    resolved_date: null,
  },
];

// --- Commodities & Indices (Phase 12) — temporary until backend is hosted ---

export const MARKET_DEFINITIONS: MarketDefinition[] = [
  {
    market_code: 'GOLD',
    market_name: 'Gold',
    asset_class: 'commodity',
    report_type: 'disaggregated',
    cftc_code: '088691',
    contract_size: '100 troy oz',
    primary_correlation_currency: 'USD',
    correlation_strength: '-0.78',
  },
  {
    market_code: 'CRUDE_OIL',
    market_name: 'Crude Oil (WTI)',
    asset_class: 'commodity',
    report_type: 'disaggregated',
    cftc_code: '067651',
    contract_size: '1,000 barrels',
    primary_correlation_currency: 'CAD',
    correlation_strength: '-0.80',
  },
  {
    market_code: 'SILVER',
    market_name: 'Silver',
    asset_class: 'commodity',
    report_type: 'disaggregated',
    cftc_code: '084691',
    contract_size: '5,000 troy oz',
    primary_correlation_currency: 'USD',
    correlation_strength: '-0.65',
  },
  {
    market_code: 'COPPER',
    market_name: 'Copper',
    asset_class: 'commodity',
    report_type: 'disaggregated',
    cftc_code: '085692',
    contract_size: '25,000 lbs',
    primary_correlation_currency: 'AUD',
    correlation_strength: '0.78',
  },
  {
    market_code: 'SP500',
    market_name: 'S&P 500 E-mini',
    asset_class: 'index',
    report_type: 'tff',
    cftc_code: '13874A',
    contract_size: '$50 x index',
    primary_correlation_currency: null,
    correlation_strength: null,
  },
  {
    market_code: 'NASDAQ100',
    market_name: 'Nasdaq 100 E-mini',
    asset_class: 'index',
    report_type: 'tff',
    cftc_code: '20974A',
    contract_size: '$20 x index',
    primary_correlation_currency: null,
    correlation_strength: null,
  },
  {
    market_code: 'VIX',
    market_name: 'VIX Futures',
    asset_class: 'index',
    report_type: 'tff',
    cftc_code: '1170E1',
    contract_size: '$1,000 x index',
    primary_correlation_currency: null,
    correlation_strength: null,
  },
];

export const COMMODITY_ANALYSES: Record<string, CommodityAnalysis> = {
  GOLD: {
    report: {
      market_code: 'GOLD',
      report_date: '2026-05-26',
      open_interest: 520000,
      open_interest_total_change: 6000,
      categories: [
        { category: 'producer_merchant', long_contracts: 120000, short_contracts: 245000, net_contracts: -125000 },
        { category: 'swap_dealer', long_contracts: 90000, short_contracts: 40000, net_contracts: 50000 },
        { category: 'managed_money', long_contracts: 180000, short_contracts: 60000, net_contracts: 120000 },
        { category: 'other_reportable', long_contracts: 30000, short_contracts: 25000, net_contracts: 5000 },
        { category: 'non_reportable', long_contracts: 20000, short_contracts: 30000, net_contracts: -10000 },
      ],
    },
    hedge_ratio: { hedge_ratio_percentage: '5.4', signal: 'under_hedged_bullish' },
    commercial_speculator: {
      commercial_net: -75000,
      speculator_net: 120000,
      is_divergent: true,
      signal: 'divergent_commercials_bullish',
    },
    phase: 'trend',
    producer_net: -125000,
    managed_money_net: 120000,
  },
  CRUDE_OIL: {
    report: {
      market_code: 'CRUDE_OIL',
      report_date: '2026-05-26',
      open_interest: 1700000,
      open_interest_total_change: 12000,
      categories: [
        { category: 'producer_merchant', long_contracts: 200000, short_contracts: 520000, net_contracts: -320000 },
        { category: 'swap_dealer', long_contracts: 240000, short_contracts: 90000, net_contracts: 150000 },
        { category: 'managed_money', long_contracts: 300000, short_contracts: 120000, net_contracts: 180000 },
        { category: 'other_reportable', long_contracts: 70000, short_contracts: 60000, net_contracts: 10000 },
        { category: 'non_reportable', long_contracts: 40000, short_contracts: 60000, net_contracts: -20000 },
      ],
    },
    hedge_ratio: { hedge_ratio_percentage: '7.6', signal: 'under_hedged_bullish' },
    commercial_speculator: {
      commercial_net: -170000,
      speculator_net: 180000,
      is_divergent: true,
      signal: 'divergent_commercials_bullish',
    },
    phase: 'trend',
    producer_net: -320000,
    managed_money_net: 180000,
  },
  SILVER: {
    report: {
      market_code: 'SILVER',
      report_date: '2026-05-26',
      open_interest: 150000,
      open_interest_total_change: 2000,
      categories: [
        { category: 'producer_merchant', long_contracts: 22000, short_contracts: 58000, net_contracts: -36000 },
        { category: 'swap_dealer', long_contracts: 18000, short_contracts: 9000, net_contracts: 9000 },
        { category: 'managed_money', long_contracts: 40000, short_contracts: 20000, net_contracts: 20000 },
        { category: 'other_reportable', long_contracts: 9000, short_contracts: 7000, net_contracts: 2000 },
        { category: 'non_reportable', long_contracts: 8000, short_contracts: 6000, net_contracts: 2000 },
      ],
    },
    hedge_ratio: { hedge_ratio_percentage: '6.4', signal: 'under_hedged_bullish' },
    commercial_speculator: {
      commercial_net: -27000,
      speculator_net: 20000,
      is_divergent: false,
      signal: 'aligned',
    },
    phase: 'trend',
    producer_net: -36000,
    managed_money_net: 20000,
  },
  COPPER: {
    report: {
      market_code: 'COPPER',
      report_date: '2026-05-26',
      open_interest: 250000,
      open_interest_total_change: -3000,
      categories: [
        { category: 'producer_merchant', long_contracts: 60000, short_contracts: 95000, net_contracts: -35000 },
        { category: 'swap_dealer', long_contracts: 40000, short_contracts: 30000, net_contracts: 10000 },
        { category: 'managed_money', long_contracts: 70000, short_contracts: 90000, net_contracts: -20000 },
        { category: 'other_reportable', long_contracts: 20000, short_contracts: 18000, net_contracts: 2000 },
        { category: 'non_reportable', long_contracts: 15000, short_contracts: 14000, net_contracts: 1000 },
      ],
    },
    hedge_ratio: { hedge_ratio_percentage: '8.6', signal: 'under_hedged_bullish' },
    commercial_speculator: {
      commercial_net: -25000,
      speculator_net: -20000,
      is_divergent: false,
      signal: 'aligned',
    },
    phase: 'capitulation',
    producer_net: -35000,
    managed_money_net: -20000,
  },
};

export const GOLD_HISTORY: CommodityHistoryPoint[] = [
  { report_date: '2026-05-12', producer_net: -109000, managed_money_net: 96000, open_interest: 520000 },
  { report_date: '2026-05-19', producer_net: -117000, managed_money_net: 108000, open_interest: 520000 },
  { report_date: '2026-05-26', producer_net: -125000, managed_money_net: 120000, open_interest: 520000 },
];

export const INDEX_REPORTS: Record<string, IndexReport> = {
  SP500: {
    market_code: 'SP500',
    report_date: '2026-05-26',
    leveraged_funds_net: 120000,
    asset_manager_net: 250000,
    dealer_net: -370000,
    open_interest: 2400000,
    open_interest_total_change: 20000,
  },
  NASDAQ100: {
    market_code: 'NASDAQ100',
    report_date: '2026-05-26',
    leveraged_funds_net: 45000,
    asset_manager_net: 60000,
    dealer_net: -105000,
    open_interest: 260000,
    open_interest_total_change: 3000,
  },
  VIX: {
    market_code: 'VIX',
    report_date: '2026-05-26',
    leveraged_funds_net: -40000,
    asset_manager_net: 15000,
    dealer_net: 25000,
    open_interest: 320000,
    open_interest_total_change: -4000,
  },
};

export const RISK_SENTIMENT: RiskSentiment = {
  score_date: '2026-05-26',
  score: '64.2',
  regime: 'neutral',
  components: [
    { name: 'sp500_managed_money', net_position: 120000, component_score: '100.0', weight: '0.35' },
    { name: 'vix_managed_money', net_position: -40000, component_score: '76.7', weight: '0.25' },
    { name: 'gold_managed_money', net_position: 120000, component_score: '0.0', weight: '0.20' },
    { name: 'jpy_leveraged_funds', net_position: -50000, component_score: '83.3', weight: '0.20' },
  ],
};

export const MULTI_ASSET_OVERVIEW: MultiAssetOverview = {
  risk_sentiment: RISK_SENTIMENT,
  commodities: (['GOLD', 'CRUDE_OIL', 'SILVER', 'COPPER'] as MarketCode[]).map((code) => {
    const analysis = COMMODITY_ANALYSES[code];
    return {
      market_code: code,
      market_name: MARKET_DEFINITIONS.find((market) => market.market_code === code)!.market_name,
      phase: analysis.phase,
      hedge_signal: analysis.hedge_ratio.signal,
      producer_net: analysis.producer_net,
      managed_money_net: analysis.managed_money_net,
    };
  }),
  indices: (['SP500', 'NASDAQ100', 'VIX'] as MarketCode[]).map((code) => ({
    market_code: code,
    market_name: MARKET_DEFINITIONS.find((market) => market.market_code === code)!.market_name,
    leveraged_funds_net: INDEX_REPORTS[code].leveraged_funds_net,
  })),
};
